// Generated by scripts/gen_rtl_pkg.py from hls/voxlio_config.hpp. Do not edit.
/* verilator lint_off UNUSEDPARAM */  // some constants exist for the host and the docs
package voxlio_pkg;

  // ---- Scan and grid --------------------------------------------------
  localparam int MAX_POINTS     = 32768;
  localparam int SCAN_AW        = 15;
  localparam int NX             = 32;
  localparam int NY             = 32;
  localparam int NZ             = 8;
  localparam int NUM_VOXELS     = 8192;
  localparam int MAP_AW         = 13;
  localparam int IX_W           = 5;
  localparam int IY_W           = 5;
  localparam int IZ_W           = 3;
  localparam int NEIGHBOR_RADIUS = 1;
  localparam int NUM_CANDIDATES = 27;
  localparam int CAND_W         = 5;

  // ---- Fixed-point formats: total width / fraction bits ------------------
  localparam int COORD_W   = 24;
  localparam int COORD_F   = 14;
  localparam int NORMAL_W  = 18;
  localparam int NORMAL_F  = 16;
  localparam int COMPUTE_W = 32;
  localparam int COMPUTE_F = 16;
  localparam int ACCUM_W   = 64;
  localparam int ACCUM_F   = 32;
  localparam int GRID_W    = 26;
  localparam int GRID_F    = 14;
  localparam bit ROUND_TO_NEAREST = 1;

  // Operand widths of the accumulator multipliers (low slices of compute_t).
  localparam int JAC_MUL_W = 22;
  localparam int RES_MUL_W = 18;

  // ---- Constants in raw fixed point -----------------------------------
  localparam logic signed [COORD_W-1:0] MAP_X_MIN_RAW = -135168;
  localparam logic signed [COORD_W-1:0] MAP_Y_MIN_RAW = -135168;
  localparam logic signed [COORD_W-1:0] MAP_Z_MIN_RAW = -36864;
  localparam logic signed [COORD_W-1:0] INV_VOXEL_RAW = 32768;
  localparam logic signed [COMPUTE_W-1:0] THRESHOLD_RAW = 19661;

  // ---- Memory word layouts -------------------------------------------
  localparam int SCAN_W = 3 * COORD_W;                  // {z, y, x}
  localparam int MAP_W  = 3 * COORD_W + 3 * NORMAL_W + 1; // {valid, nz, ny, nx, cz, cy, cx}

  // ---- Status word -----------------------------------------------------
  localparam logic [31:0] STATUS_SUCCESS        = 32'h01;
  localparam logic [31:0] STATUS_ZERO_INLIERS   = 32'h02;
  localparam logic [31:0] STATUS_BAD_MAP_CONFIG = 32'h04;
  localparam logic [31:0] STATUS_BAD_POSE       = 32'h08;
  localparam logic [31:0] STATUS_POINT_OVERFLOW = 32'h10;
  localparam logic [31:0] STATUS_OOB_PREVENTED  = 32'h20;

  // ---- Helpers -----------------------------------------------------------
  // |x| with ap_fixed AP_SAT semantics: the most negative value maps to the
  // most positive one instead of overflowing.
  function automatic logic signed [COMPUTE_W-1:0] sat_abs(input logic signed [COMPUTE_W-1:0] x);
    if (!x[COMPUTE_W-1]) return x;
    if (x == {1'b1, {(COMPUTE_W-1){1'b0}}}) return {1'b0, {(COMPUTE_W-1){1'b1}}};
    return -x;
  endfunction

endpackage
