#!/usr/bin/env python3
"""Measure the CPU baseline: the plain C++ reference, single thread.

Builds testbench/bench_cpu.cpp with -O2 (no sanitizers), runs it on every
synthetic case and writes results/benchmark/cpu_reference.md. These are
software timings on this machine; they say nothing about the accelerator.
"""

import datetime
import pathlib
import platform
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "synthetic"
BINARY = ROOT / "build" / "bench" / "bench_cpu"
FLAGS = ["-std=c++14", "-O2", "-ffp-contract=off"]
REPEATS = 200


def cpu_model():
    for line in pathlib.Path("/proc/cpuinfo").read_text().splitlines():
        if line.startswith("model name"):
            return line.split(":", 1)[1].strip()
    return platform.processor() or "unknown"


def read_meta(case):
    meta = {}
    for line in (DATA / case / "meta.txt").read_text().splitlines():
        key, _, value = line.partition(" ")
        meta[key] = value
    return meta


def main():
    cases = sys.argv[1:] or sorted(p.name for p in DATA.iterdir() if (p / "meta.txt").exists())
    BINARY.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(["g++", *FLAGS, "-Ihls", "-Ireference/cpp", "-Itestbench",
                    "testbench/bench_cpu.cpp", "reference/cpp/voxlio_ref.cpp", "-o", str(BINARY)],
                   cwd=ROOT, check=True)
    compiler = subprocess.run(["g++", "--version"], capture_output=True, text=True).stdout.splitlines()[0]

    lines = [
        "# CPU reference timing",
        "",
        f"Generated by `scripts/bench_cpu.py` on {datetime.date.today().isoformat()}.",
        "",
        f"- Implementation: `reference/cpp/voxlio_ref.cpp` (plain C++, float, single thread)",
        f"- CPU: {cpu_model()}",
        f"- Compiler: {compiler}, flags `{' '.join(FLAGS)}`",
        f"- Each figure is the median of {REPEATS} runs of one scan (minimum in brackets).",
        "",
        "| case | points/scan | voxel size (m) | valid voxels | valid candidates/point | "
        "runtime (ms) | throughput (points/s) | ns/point |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for case in cases:
        out = subprocess.run([str(BINARY), str(DATA / case), str(REPEATS)], capture_output=True,
                             text=True, check=True).stdout.split()
        fields = dict(zip(out[::2], out[1::2]))
        meta = read_meta(case)
        points = int(fields["points"])
        median, minimum = float(fields["median_ms"]), float(fields["min_ms"])
        lines.append(
            f"| {case} | {points} | {meta['voxel_size']} | {meta['valid_voxels']} | "
            f"{float(meta['candidates_valid_per_point']):.2f} | {median:.3f} ({minimum:.3f}) | "
            f"{points / median * 1e3:,.0f} | {median * 1e6 / points:.1f} |")
    lines.append("")

    out_path = ROOT / "results" / "benchmark" / "cpu_reference.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
