#!/usr/bin/env python3
"""Generate rtl/voxlio_pkg.sv from hls/voxlio_config.hpp.

The header stays the single source of truth; this script turns its values
into SystemVerilog localparams, converting the metric constants to raw
fixed-point integers exactly as the ap_fixed C++ build does (round half up,
saturate).
"""

import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from reference import config as cfg  # noqa: E402

OUT = ROOT / "rtl" / "voxlio_pkg.sv"


def to_raw(value, width, fraction):
    """ap_fixed<width, width - fraction, AP_RND, AP_SAT> constructed from a double."""
    raw = math.floor(value * 2 ** fraction + 0.5)
    top = 2 ** (width - 1)
    return max(-top, min(top - 1, raw))


def clog2(n):
    return max(1, (n - 1).bit_length())


def main():
    f = {name: (w, w - i) for name, (w, i) in cfg.FIXED_FORMATS.items()}  # (width, fraction)
    coord_w, coord_f = f["COORD"]
    normal_w, normal_f = f["NORMAL"]
    compute_w, compute_f = f["COMPUTE"]
    accum_w, accum_f = f["ACCUM"]
    grid_w, grid_f = coord_w + 2, coord_f

    # Assumptions the RTL arithmetic is written for.
    assert coord_f + normal_f >= compute_f, "residual/Jacobian products must have at least COMPUTE_F fraction bits"
    assert normal_f <= compute_f, "normals must be exactly representable in compute_t"
    assert 2 * compute_f == accum_f, "accumulators take products of compute_t without quantisation"
    assert 2 * compute_w <= accum_w
    assert cfg.FIXED_QUANT in ("AP_RND", "AP_TRN")
    radius = cfg.NEIGHBOR_RADIUS
    candidates = (2 * radius + 1) ** 3

    # Multiplier operand widths used by the accumulator (docs/rtl.md): every
    # Jacobian entry is bounded by 2 * (grid corner radius) and every
    # accumulated residual by the threshold, so the products are formed from
    # these narrower slices. The testbench asserts the slices are lossless.
    corner = math.sqrt(sum(max(abs(m), abs(m + n * cfg.VOXEL_SIZE)) ** 2
                           for m, n in zip(cfg.MAP_MIN, cfg.GRID_DIMS)))
    jac_int = clog2(math.ceil(2.0 * corner)) + 1          # sign + integer bits for |J| <= 2*corner
    res_int = clog2(math.ceil(cfg.RESIDUAL_THRESHOLD)) + 1  # sign + integer bits for |r| < threshold
    jac_mul_w = min(compute_w, compute_f + jac_int)
    res_mul_w = min(compute_w, compute_f + res_int)

    lines = [
        "// Generated by scripts/gen_rtl_pkg.py from hls/voxlio_config.hpp. Do not edit.",
        "/* verilator lint_off UNUSEDPARAM */  // some constants exist for the host and the docs",
        "package voxlio_pkg;",
        "",
        "  // ---- Scan and grid --------------------------------------------------",
        f"  localparam int MAX_POINTS     = {cfg.MAX_POINTS};",
        f"  localparam int SCAN_AW        = {clog2(cfg.MAX_POINTS)};",
        f"  localparam int NX             = {cfg.NX};",
        f"  localparam int NY             = {cfg.NY};",
        f"  localparam int NZ             = {cfg.NZ};",
        f"  localparam int NUM_VOXELS     = {cfg.NUM_VOXELS};",
        f"  localparam int MAP_AW         = {clog2(cfg.NUM_VOXELS)};",
        f"  localparam int IX_W           = {clog2(cfg.NX)};",
        f"  localparam int IY_W           = {clog2(cfg.NY)};",
        f"  localparam int IZ_W           = {clog2(cfg.NZ)};",
        f"  localparam int NEIGHBOR_RADIUS = {radius};",
        f"  localparam int NUM_CANDIDATES = {candidates};",
        f"  localparam int CAND_W         = {clog2(candidates + 1)};",
        "",
        "  // ---- Fixed-point formats: total width / fraction bits ------------------",
        f"  localparam int COORD_W   = {coord_w};",
        f"  localparam int COORD_F   = {coord_f};",
        f"  localparam int NORMAL_W  = {normal_w};",
        f"  localparam int NORMAL_F  = {normal_f};",
        f"  localparam int COMPUTE_W = {compute_w};",
        f"  localparam int COMPUTE_F = {compute_f};",
        f"  localparam int ACCUM_W   = {accum_w};",
        f"  localparam int ACCUM_F   = {accum_f};",
        f"  localparam int GRID_W    = {grid_w};",
        f"  localparam int GRID_F    = {grid_f};",
        f"  localparam bit ROUND_TO_NEAREST = {1 if cfg.FIXED_QUANT == 'AP_RND' else 0};",
        "",
        "  // Operand widths of the accumulator multipliers (low slices of compute_t).",
        f"  localparam int JAC_MUL_W = {jac_mul_w};",
        f"  localparam int RES_MUL_W = {res_mul_w};",
        "",
        "  // ---- Constants in raw fixed point -----------------------------------",
        f"  localparam logic signed [COORD_W-1:0] MAP_X_MIN_RAW = {to_raw(cfg.MAP_MIN[0], coord_w, coord_f)};",
        f"  localparam logic signed [COORD_W-1:0] MAP_Y_MIN_RAW = {to_raw(cfg.MAP_MIN[1], coord_w, coord_f)};",
        f"  localparam logic signed [COORD_W-1:0] MAP_Z_MIN_RAW = {to_raw(cfg.MAP_MIN[2], coord_w, coord_f)};",
        f"  localparam logic signed [COORD_W-1:0] INV_VOXEL_RAW = {to_raw(1.0 / cfg.VOXEL_SIZE, coord_w, coord_f)};",
        f"  localparam logic signed [COMPUTE_W-1:0] THRESHOLD_RAW = {to_raw(cfg.RESIDUAL_THRESHOLD, compute_w, compute_f)};",
        "",
        "  // ---- Memory word layouts -------------------------------------------",
        "  localparam int SCAN_W = 3 * COORD_W;                  // {z, y, x}",
        "  localparam int MAP_W  = 3 * COORD_W + 3 * NORMAL_W + 1; // {valid, nz, ny, nx, cz, cy, cx}",
        "",
        "  // ---- Status word -----------------------------------------------------",
        f"  localparam logic [31:0] STATUS_SUCCESS        = 32'h{cfg.STATUS_SUCCESS:02x};",
        f"  localparam logic [31:0] STATUS_ZERO_INLIERS   = 32'h{cfg.STATUS_ZERO_INLIERS:02x};",
        f"  localparam logic [31:0] STATUS_BAD_MAP_CONFIG = 32'h{cfg.STATUS_BAD_MAP_CONFIG:02x};",
        f"  localparam logic [31:0] STATUS_BAD_POSE       = 32'h{cfg.STATUS_BAD_POSE:02x};",
        f"  localparam logic [31:0] STATUS_POINT_OVERFLOW = 32'h{cfg.STATUS_POINT_OVERFLOW:02x};",
        f"  localparam logic [31:0] STATUS_OOB_PREVENTED  = 32'h{cfg.STATUS_OOB_PREVENTED:02x};",
        "",
        "  // ---- Helpers -----------------------------------------------------------",
        "  // |x| with ap_fixed AP_SAT semantics: the most negative value maps to the",
        "  // most positive one instead of overflowing.",
        "  function automatic logic signed [COMPUTE_W-1:0] sat_abs(input logic signed [COMPUTE_W-1:0] x);",
        "    if (!x[COMPUTE_W-1]) return x;",
        "    if (x == {1'b1, {(COMPUTE_W-1){1'b0}}}) return {1'b0, {(COMPUTE_W-1){1'b1}}};",
        "    return -x;",
        "  endfunction",
        "",
        "endpackage",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
