#!/usr/bin/env python3
"""Host-loop experiment on the synthetic room.

Iterates  accelerator model -> 6 x 6 solve -> pose update  from the predicted
pose and reports the distance to the ground-truth pose after every iteration.
Run for the room with its planes at voxel centres and on voxel faces, with and
without the optional planarity gate of the map builder, and with the search
reduced to the point's own voxel (neighbour radius 0, open question Q6).

Writes results/benchmark/pose_convergence.md.
"""

import datetime
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from reference import config as cfg                                      # noqa: E402
from reference import generate_synthetic as gen                         # noqa: E402
from reference.geometry import apply_delta, pose_error, solve_update     # noqa: E402
from reference.voxel_map import build_voxel_map                          # noqa: E402
from reference.voxlio_reference import run                               # noqa: E402

ITERATIONS = 5
CENTRED = gen.Scene()
ON_FACES = gen.Scene(ground_z=0.25, wall_x=4.25, wall_y=4.25)

# (name, scene, planarity gate of the map builder, neighbour radius)
EXPERIMENTS = [
    ("planes at voxel centres (case `room`)", CENTRED, None, 1),
    ("planes at voxel centres, planarity gate 0.05", CENTRED, 0.05, 1),
    ("planes at voxel centres, own voxel only (radius 0)", CENTRED, None, 0),
    ("planes on voxel faces (case `room_face_aligned`)", ON_FACES, None, 1),
    ("planes on voxel faces, planarity gate 0.05", ON_FACES, 0.05, 1),
    ("planes on voxel faces, own voxel only (radius 0)", ON_FACES, None, 0),
]


def converge(scene, max_thickness_ratio, radius):
    # The golden model reads the radius at call time; every other
    # implementation takes it from voxlio_config.hpp at build time.
    cfg.NEIGHBOR_RADIUS = radius
    R_gt, t_gt = gen.ground_truth_pose()
    R, t = gen.predicted_pose(R_gt, t_gt)
    scan = gen.make_scan(R_gt, t_gt, scene)
    vmap = build_voxel_map(gen.make_map_points(scene), max_thickness_ratio=max_thickness_ratio)

    errors = [pose_error(R, t, R_gt, t_gt)]
    inliers = None
    for _ in range(ITERATIONS):
        result = run(scan, len(scan), vmap, R, t)
        inliers = inliers or result.inlier_count
        R, t = apply_delta(R, t, solve_update(result.H, result.g, result.inlier_count))
        errors.append(pose_error(R, t, R_gt, t_gt))
    return len(scan), int(vmap.valid.sum()), inliers, errors


def main():
    head = ["experiment", "points", "valid voxels", "inliers (iter 1)", "start"] + [
        f"iter {i}" for i in range(1, ITERATIONS + 1)]
    lines = [
        "# Pose convergence on the synthetic room",
        "",
        f"Generated by `scripts/pose_convergence.py` on {datetime.date.today().isoformat()}"
        " with the float32 golden model.",
        "",
        "Each cell is the distance to the ground-truth pose: translation in mm / rotation in",
        "degrees. The predicted pose starts 87.5 mm and 1.118 degrees away. Map and scan",
        "carry 1 cm Gaussian range noise.",
        "",
        "| " + " | ".join(head) + " |",
        "|" + "---|" * len(head),
    ]
    for name, scene, ratio, radius in EXPERIMENTS:
        points, voxels, inliers, errors = converge(scene, ratio, radius)
        cells = [f"{dist * 1e3:.2f} / {np.rad2deg(angle):.4f}" for angle, dist in errors]
        lines.append("| " + " | ".join([name, str(points), str(voxels), str(inliers), *cells]) + " |")
        print(lines[-1])
    lines.append("")

    out = ROOT / "results" / "benchmark" / "pose_convergence.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
