#!/usr/bin/env python3
"""Summarise a Quartus compile of quartus/voxlio (verification level 5).

Reads quartus/output_files/voxlio.fit.summary and voxlio.sta.rpt, writes
results/synthesis/quartus_summary.md. Only values found in the reports are
printed; nothing is estimated here.

NOTE: written against the documented report formats without access to
Quartus; check the first real summary against the reports.
"""

import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "quartus" / "output_files"
SUMMARY = ROOT / "results" / "synthesis" / "quartus_summary.md"

FIT_KEYS = [
    "Quartus Prime Version", "Fitter Status", "Top-level Entity Name", "Family", "Device",
    "Logic utilization (in ALMs)", "Total registers", "Total block memory bits",
    "Total RAM Blocks", "Total DSP Blocks", "Total virtual pins",
]


def fit_summary(path):
    values = {}
    for line in path.read_text(errors="replace").splitlines():
        key, sep, value = line.partition(" : ")
        if sep and key.strip() in FIT_KEYS:
            values[key.strip()] = value.strip()
    return values


def fmax(path):
    """(corner, fmax) pairs from the 'Fmax Summary' tables of the STA report."""
    results = []
    text = path.read_text(errors="replace")
    for m in re.finditer(r";\s*([^;\n]*Model Fmax Summary)\s*;\s*\n(.*?)\n\n", text, re.S):
        corner = m.group(1).strip()
        for row in m.group(2).splitlines():
            cells = [c.strip() for c in row.strip().strip(";").split(";")]
            if len(cells) >= 3 and re.match(r"[\d.]+ MHz", cells[0]):
                results.append((corner, cells[0], cells[1], cells[2]))
                break
    return results


def main():
    fit = OUT_DIR / "voxlio.fit.summary"
    sta = OUT_DIR / "voxlio.sta.rpt"
    if not fit.exists():
        sys.exit(f"{fit} not found; run `quartus_sh --flow compile voxlio` in quartus/ first")

    values = fit_summary(fit)
    lines = [
        "# VoxLIO Quartus summary",
        "",
        f"Generated by `scripts/summarize_quartus.py` on {datetime.date.today().isoformat()}"
        " from quartus/output_files. Fitter results for the core alone with virtual pins;",
        "no HPS wrapper.",
        "",
        "| metric | value |",
        "|---|---|",
    ]
    for key in FIT_KEYS:
        lines.append(f"| {key} | {values.get(key, 'n/a')} |")
    if sta.exists():
        for corner, f, restricted, clock in fmax(sta):
            lines.append(f"| Fmax ({corner}, {clock}) | {f} (restricted {restricted}) |")
    else:
        lines.append("| Fmax | n/a (no sta.rpt) |")
    lines.append("")

    SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY.write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
